question_data = [
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "A group of islands is called an &#039;archipelago&#039;.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean",
     "difficulty": "easy",
     "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004&#039;s &quot;The Aviator&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "History", "type": "boolean", "difficulty": "medium",
     "question": "The first televised presidential debate was between Jimmy Carter and Gerald Ford.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "Tetris is the #1 best-selling video game of all-time.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "General Knowledge", "type": "boolean",
     "difficulty": "easy",
     "question": "You can legally drink alcohol while driving in Mississippi.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "History", "type": "boolean", "difficulty": "easy",
     "question": "Former United States Presidents John Adams and Thomas Jefferson died within hours of each other.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean",
     "difficulty": "easy",
     "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science & Nature", "type": "boolean",
     "difficulty": "easy",
     "question": "Water always boils at 100&deg;C, 212&deg;F, 373.15K, no matter where you are.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean",
     "difficulty": "easy",
     "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Film", "type": "boolean",
     "difficulty": "hard",
     "question": "YouTube personality Jenna Marbles served as an executive producer of the film Maximum Ride (2016).",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
